config/routes.rb
Rails.application.routes.draw do
  get 'search/show'

  root to: 'categories#index'
  devise_for :users, controllers: { registrations: 'registrations/registrations' }
  resources :users do
    resources :auctions, only: :index
    resources :received_comments, only: :index, controller: :comments
  end

  get '/search', to: 'search#show'
  get '/auctions/:id/end_prematurely', to: 'auctions#end_prematurely', as: 'auction_end_prematurely'

  resources :categories, only: [:new, :create, :edit, :update, :destroy, :index] do
    resources :auctions do
      resources :bids, only: [:new, :create]
    end
  end

  resources :auctions, only: [:new, :create, :index, :edit, :update, :destroy] do
    resources :comments, only: [:new, :create]
  end
end

app/models/auction.rb
class Auction < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :bids, dependent: :destroy
  has_one :seller_comment, class_name: "Comment", foreign_key: :auction_id, dependent: :nullify
  has_one :buyer_comment, class_name: "Comment", foreign_key: :auction_id, dependent: :nullify

  validates :category, presence: true
  validates :user, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :price, presence: true, numericality: { greater_than: 0, less_than: 100000000 }

  validates :auction_type, inclusion: {
    in: %w(instant classic),
    message: "its type has to be 'instant' or 'classic'"
  }

  validates :title, presence: true, allow_blank: false, length: {
    maximum: 40,
    too_long: "length has to be up to 40"
  }
  validates :description, presence: true, allow_blank: false, length: {
    maximum: 1000,
    too_long: "length has to be up to 1000"
  }

  validates_datetime :start_date, before: :end_date

  validate :up_to_one_bid, if: :instant_auction?

  # This is ugly as hell, but it's a part of our school assignment to do it
  # like this. Sorry.
  def end_prematurely
    connection = ActiveRecord::Base.connection.raw_connection
    connection.exec("select end_auction(#{id})")
  end

  def self.search_title(by, also_descriptions)
    search_condition = ("%" + by + "%").downcase
    if also_descriptions
      where(['lower(title) like ? or lower(description) like ?', search_condition, search_condition])
    else
      where(['lower(title) like ?', search_condition])
    end
  end

  def self.search_min_price(min)
    where(['price >= ?', min.to_f])
  end

  def self.search_max_price(max)
    where(['price <= ?', max.to_f])
  end

  def self.search_auction_type(auc_t)
    where(['auction_type = ?', auc_t])
  end

  # Default accessors seem not to work properly, both returning the same
  # comment, hence the overridden ones below. It's sort of a TODO.
  def buyer_comment
    Comment.find_by(id: self.buyer_comment_id)
  end

  def seller_comment
    Comment.find_by(id: self.seller_comment_id)
  end

  def instant_auction?
    auction_type == 'instant'
  end

  def has_bids_by?(user)
    true unless bids.all.select { |b| b.user == user }.blank?
  end

  def is_finished?
    if auction_type == 'instant'
      return true if bids.present?
    elsif auction_type == 'classic'
      return true if DateTime.now > end_date
    end
  end

  def up_to_one_bid
    errors.add(:bids, "number should be limited to 1 for an instant") if bids.count > 1
  end

  def winner
    return bids.order('price desc').first.user if bids.present?
    return nil
  end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  expose_decorated :auction
  expose_decorated(:auctions) { filtered_auctions }
  expose :category
  expose :user
  expose(:bids) { auction.bids }
  expose :contract
  expose(:parent) { parent_str }

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def create
    self.auction = Auction.new(auction_params)
    auction.user = current_user
    auction.start_date = DateTime.now

    if auction.save
      auctions << auction
      redirect_to category_auction_url(auction.category, auction), notice: 'Auction successfully created'
    else
      render 'auctions/new'
    end
  end

  def update
    self.auction = Auction.find(params['id'])
    if auction.update(update_params)
      redirect_to category_auction_url(auction.category, auction), notice: 'Auction successfully updated'
    else
      render 'auctions/edit'
    end
  end

  def destroy
    auction.destroy
    redirect_to category_auctions_url(auction.category), notice: 'Auction deleted successfully'
  end

  def end_prematurely
    auction.end_prematurely
    redirect_to category_auction_url(auction.category, auction), notice: 'Auction ended prematurely'
  end

  private

  def filtered_auctions
    if parent_object.nil?
      filtered = Auction.all
    else
      filtered = parent_object.auctions
    end
    filtered = filtered.search_title(params['title'], params['also_descriptions'].present?) if params['title'].present?
    filtered = filtered.search_min_price(BigDecimal.new(params['min_price'])) if params['min_price'].present?
    filtered = filtered.search_max_price(BigDecimal.new(params['max_price'])) if params['max_price'].present?
    filtered = filtered.search_auction_type(params['auction_type']) if params['auction_type'].present?
    filtered = filtered.paginate(page: params['page'], per_page: 30)
  end

  def parent_object
    if params['user_id']
      User.find_by(id: params['user_id'])
    elsif params['category_id']
      Category.find_by(id: params['category_id'])
    end
  end

  def parent_str
    if parent_object.class == User
      parent_object.email
    elsif parent_object.class == Category
      parent_object.title
    end
  end

  def auction_params
    params.require(:auction).permit(:id, :price, :title, :description, :auction_type, :start_date, :end_date, :category_id, :user_id)
  end

  def update_params
    params['auction'].permit(:description, :category_id)
  end
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/views/auctions/create.html.haml
%h1 Auctions#create
%p Find me in app/views/auctions/create.html.haml

app/views/auctions/destroy.html.haml
%h1 Auctions#destroy
%p Find me in app/views/auctions/destroy.html.haml

app/views/auctions/edit.html.haml
%h1 Editing auction

= simple_form_for [category, auction] do |f|
  = render 'shared/error_messages', object: f.object
  .inputs
    = f.input :category_id, collection: Category.all
    = f.input :description, as: :text
  .actions
    = f.button :submit

app/views/auctions/index.html.haml
%h1
  = "All auctions: #{parent}"
- if params['title'].present?
  %h4
    = "Title: #{params['title']}"
    - if params['also_descriptions']
      (also in descriptions)
- if params['min_price'].present?
  %h4= "Minimum price: #{params['min_price']}"
- if params['max_price'].present?
  %h4= "Maximum price: #{params['max_price']}"
- if params['auction_type'].present?
  %h4= "Auction type: #{params['auction_type']}"


%small.float-right
  = link_to new_auction_path do
    %span.glyphicon.glyphicon-plus
    New auction

%table.table
  %thead
    %tr
      %th Title
      %th Auction type
      %th Price
      %th Bids
      %th End date
      %th Created by
      %th
      %th

  %tfoot.apple_pagination
    %tr
      %td.text-center{colspan: 7}= page_entries_info auctions
    %tr
      %td.text-center{colspan: 7}= will_paginate auctions, container: false

  %tbody
    - if not auctions.empty?
      - auctions.each do |auction|
        %tr
          %td= link_to auction.title, category_auction_path(auction.category, auction)
          %td= auction.auction_type
          %td= auction.current_price
          %td= auction.bids.count
          %td= auction.end_date.in_time_zone('Warsaw').to_formatted_s(:long)
          %td= link_to auction.user.name, auction.user
          - if current_user and (auction.user == current_user or current_user.admin?)
            %td= link_to "Edit", edit_category_auction_path(auction.category, auction)
            %td= link_to "Delete", category_auction_path(auction.category, auction), method: :delete, data: { confirm: 'Sure?' }
          - else
            %td &nbsp;
            %td &nbsp;

app/views/auctions/new.html.haml
%h1 Create a new auction

= simple_form_for auction do |f|
  = render 'shared/error_messages', object: f.object
  .inputs
    = f.input :title
    = f.input :category_id, collection: Category.all
    = f.input :description, as: :text
    = f.input :auction_type, as: :radio_buttons, collection: [:instant, :classic]
    = f.input :price
    = f.input :end_date, as: :datetime_picker
  .actions
    = f.button :submit

app/views/auctions/show.html.haml
.jumbotron
  %h2
    = link_to category.title, category_auctions_url(category)
    |
    = auction.title

  %table.table.summary-table
    - if user_signed_in? && auction.is_finished? && auction.winner == current_user
      .alert.alert-info
        %b
          = "Congratulations, you have won this auction."
          %br
        = "Please transfer #{auction.current_price} to the following bank account:"
        %br
        = ISO::IBAN.parse(auction.user.account_number).formatted
    - elsif auction.has_bids_by? current_user
      .alert.alert-info
        = "You have bid #{pluralize(auction.bids_count_by(current_user), 'time')} in this auction."
        - if auction.winner == current_user
          Your bid is currently the highest.
        - else
          You have been outbid.
    - if auction.user == current_user
      .alert.alert-info
        This is your auction.
        - if auction.is_finished? && auction.winner.present?
          = "It has been finished and the winner is"
          %b= link_to auction.winner.email, auction.winner
          %br
          %b= "When you're paid, don't wait to send the subject to the following address: "
          %p
            = auction.winner.street
            = auction.winner.house_number
            %br
            = auction.winner.postal_code
            = auction.winner.city

        - elsif auction.is_finished?
          = "It has been finished with no bids."
        - else
          It has not been finished yet. You can
          = link_to 'end it prematurely', auction_end_prematurely_url(auction)
          if you like.
    %tr
      %td.left Description
      %td= auction.description
    %tr
      %td.left Added by
      %td= link_to auction.user.email, auction.user
    %tr
      %td.left Price
      %td
        = auction.current_price
        - unless auction.is_finished?
          = auction.bid_link
        - else
          - unless auction.winner.nil?
            = "(finished - winner: #{auction.winner.email})"
          - else
            (finished - no offers)
    %tr
      %td.left End date
      %td= auction.end_date.in_time_zone('Warsaw').to_formatted_s(:long)
    %tr
      %td.left Bids
      %td
        - unless bids.empty?
          - bids.each do |bid|
            .row
              = "#{bid.price} (#{bid.user.email})"
        - else
          This auction has no bids yet.

app/views/auctions/update.html.haml
%h1 Auctions#update
%p Find me in app/views/auctions/update.html.haml