config/routes.rb
Rails.application.routes.draw do
  get 'search/show'

  root to: 'categories#index'
  devise_for :users, controllers: { registrations: 'registrations/registrations' }
  resources :users do
    resources :auctions, only: :index
    resources :received_comments, only: :index, controller: :comments
  end

  get '/search', to: 'search#show'
  get '/auctions/:id/end_prematurely', to: 'auctions#end_prematurely', as: 'auction_end_prematurely'

  resources :categories, only: [:new, :create, :edit, :update, :destroy, :index] do
    resources :auctions do
      resources :bids, only: [:new, :create]
    end
  end

  resources :auctions, only: [:new, :create, :index, :edit, :update, :destroy] do
    resources :comments, only: [:new, :create]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  require 'iso/iban'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :auctions
  has_many :bids
  has_many :issued_comments, class_name: 'Comment', foreign_key: :author_id
  has_many :received_comments, class_name: 'Comment', foreign_key: :user_for_id

  validates :street, presence: true, allow_blank: false, length: { maximum: 100 }
  validates :city, presence: true, allow_blank: false, length: { maximum: 100 }
  validates :house_number, presence: true, allow_blank: false, length: { maximum: 10 }
  validates :postal_code, presence: true, format: { with: /[0-9]{2}\-[0-9]{3}/ }

  validate :iban_valid

  def won_auctions
    Auction.all.select { |a| a.winner == self }
  end

  # This is ugly as hell, but as a part of my school assignment I had to
  # implement some functionality like this.
  def positive_comment_rate
    connection = ActiveRecord::Base.connection.raw_connection
    connection.exec("select positive_percentage(#{id})").getvalue(0, 0).to_f
  end

  private

  def iban_valid
    if account_number.present?
      errors.add(:account_number, 'is not a valid IBAN') unless ISO::IBAN.new(account_number).valid?
    else
      errors.add(:account_number, 'cant be blank')
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/views/users/_user.html.erb
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.haml
%h3= "User: #{@user.name}"
%p= "Email: #{@user.email}"

.row

  .col-md-7
    .panel.panel-default
      .panel-heading
        Latest auctions created by user
      .panel-body
        %table.table
          %tr
            %th Auction
            %th Type
            %th Ends at
            %th Bids
            %th
              .pull-right Price
          - @user.auctions.order(:start_date).last(10).each do |auction|
            %tr
              %td= link_to "#{auction.title}", category_auction_url(auction.category, auction)
              %td= auction.auction_type
              %td
                - if auction.is_finished?
                  Finished
                - else
                  = auction.end_date.in_time_zone('Warsaw').to_formatted_s(:long)
              %td= auction.bids.count
              %td
                .pull-right= auction.price
          %tr
            %td{colspan: 5}
              .pull-right= link_to "See all #{@user.auctions.count} auctions...", user_auctions_url(@user)
      .panel-heading
        Latest auctions won by user
      .panel-body
        %table.table
          %tr
            %th Auction
            %th Created by
            %th Price
            %th
          - @user.won_auctions.sort_by { |a| a.created_at }.last(5).each do |auction|
            %tr
              %td= link_to "#{auction.title}", category_auction_url(auction.category, auction)
              %td= link_to auction.user.email, auction.user
              %td= auction.price
              %td
                - if user_signed_in? && auction.winner == current_user && auction.buyer_comment.blank?
                  = link_to "Create comment", new_auction_comment_url(auction)
      .panel-heading
        Latest finished auctions created by user
      .panel-body
        %table.table
          %tr
            %th Auction
            %th Winner
            %th Price
            %th
          - @user.auctions.select { |a| a.is_finished? }.each do |auction|
            %tr
              %td= link_to "#{auction.title}", category_auction_url(auction.category, auction)
              %td
                - if auction.bids.present?
                  = link_to auction.winner.email, auction.winner
                - else
                  No bids
              %td= auction.price
              %td
                - if current_user == auction.user && auction.bids.present? && auction.seller_comment.blank?
                  = link_to "Create comment", new_auction_comment_url(auction)

  .col-md-5
    .panel.panel-default
      .panel-heading
        = "Comments received by user (positive: #{@user.positive_comment_rate * 100}%)"
      .panel-body
        %table.table.small
          - @user.received_comments.order(:created_at).last(10).each do |comment|
            %tr{class: comment_class_for(comment)}
              %td.col-md-3
                = "#{comment.comment_type} from "
                = link_to excerpt(comment.author.email, '', radius: 7), comment.author
              %td.col-md-7= excerpt(comment.content, '', separator: ' ', radius: 20)
              %td.col-md-2= link_to 'auction', category_auction_url(comment.auction.category, comment.auction)
          %tr
            %td{colspan: 3}
              .pull-right= link_to "See all #{@user.received_comments.count} comments...", user_received_comments_url(@user)

.row

  .col-md-12
    .panel.panel-default
      .panel-heading