config/routes.rb
Rails.application.routes.draw do
  get 'search/show'

  root to: 'categories#index'
  devise_for :users, controllers: { registrations: 'registrations/registrations' }
  resources :users do
    resources :auctions, only: :index
    resources :received_comments, only: :index, controller: :comments
  end

  get '/search', to: 'search#show'
  get '/auctions/:id/end_prematurely', to: 'auctions#end_prematurely', as: 'auction_end_prematurely'

  resources :categories, only: [:new, :create, :edit, :update, :destroy, :index] do
    resources :auctions do
      resources :bids, only: [:new, :create]
    end
  end

  resources :auctions, only: [:new, :create, :index, :edit, :update, :destroy] do
    resources :comments, only: [:new, :create]
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :auctions, dependent: :destroy

  validates :title, presence: true, allow_blank: false, length: {
    maximum: 30,
    too_long: "its length has to be up to #{count}"
  }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :create]

  expose_decorated :categories
  expose_decorated :category

  def new
  end

  def create
    self.category = Category.new(category_params)
    category.title = category_params['title']

    if category.save
      categories << category
      redirect_to root_url, notice: 'Category successfully created'
    else
      render 'categories/new'
    end
  end

  def index
  end

  def destroy
    category.destroy
    redirect_to categories_url
  end

  def update
    self.category = Category.find(params['id'])
    if category.update(category_params)
      redirect_to root_url, notice: 'Category successfully renamed'
    else
      render 'categories/edit'
    end
  end

  def edit
  end

  private

  def category_params
    params.require(:category).permit(:title)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/create.html.haml
%h1 Categories#create
%p Find me in app/views/categories/create.html.haml

app/views/categories/destroy.html.haml
%h1 Categories#destroy
%p Find me in app/views/categories/destroy.html.haml

app/views/categories/edit.html.haml
%h1= "Editing category: #{category.title}"

= simple_form_for category do |f|
  = render 'shared/error_messages', object: f.object
  .inputs
    = f.input :title
  .actions
    = f.button :submit

app/views/categories/index.html.haml
.col-md-12
  %h1
    Categories
    - if current_user && current_user.admin?
      %small.float-right
        = link_to new_category_path do
          %span.glyphicon.glyphicon-plus
          New Category
- if categories.empty?
  There are no categories. Why not
  =link_to 'create one just now?', new_category_path
- categories.each_slice(3) do |slice|
  .row
    - slice.each do |category|
      .col-md-4
        .panel.panel-default
          .panel-heading
            %h3.no-vertical-margins
              = link_to category.title, category_auctions_path(category)
              - if current_user && current_user.admin?
                %small.float-right
                  = link_to edit_category_path(category) do
                    %span.glyphicon.glyphicon-edit
                    Edit
                  = link_to category, method: :delete, data: { confirm: 'Are you sure?' } do
                    %span.glyphicon.glyphicon-remove
                    Remove
          .panel-body
            - if category.auctions.empty?
              No auctions in this category. Yet.
            %ol
              - category.latest_five_auctions.each do |auction|
                %li= link_to auction.title, category_auction_path(category, auction)
            .clear-both
              %p.left

              %p.right
                = link_to category_auctions_path(category) do
                  %span.glyphicon.glyphicon-th-list
                  Show all auctions

app/views/categories/new.html.haml
%h1 New category

= simple_form_for category do |f|
  = render 'shared/error_messages', object: f.object
  .inputs
    = f.input :title
  .actions
    = f.button :submit

app/views/categories/update.html.haml
%h1 Categories#update
%p Find me in app/views/categories/update.html.haml